# Generated by Django 2.1.4 on 2019-01-20 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing', models.CharField(max_length=1, unique=True)),
                ('on_reading', models.CharField(blank=True, max_length=100)),
                ('kun_reading', models.CharField(blank=True, max_length=100)),
                ('meaning', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KanjiLearningRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_learnt', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=None, null=True)),
                ('kanji_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.KanjiEntry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
