# Generated by Django 2.1.4 on 2019-02-02 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiTestingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tested', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=None, null=True)),
                ('kanji_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.KanjiEntry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
