# Generated by Django 2.1.4 on 2019-02-10 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_kanjitestingrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanjilearningrecord',
            name='order',
        ),
        migrations.RemoveField(
            model_name='kanjitestingrecord',
            name='is_tested',
        ),
        migrations.RemoveField(
            model_name='kanjitestingrecord',
            name='order',
        ),
        migrations.AddField(
            model_name='kanjitestingrecord',
            name='correct_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kanjitestingrecord',
            name='test_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
